/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface JobDto {
  jobKey: string;
  jobName: string;
  /**
   * Last jobId
   */
  jobId?: string;
  jobStatus?: "SUBMITTED" | "STARTING" | "RUNNING" | "FAILED" | "SUCCEEDED";
}
